services:
  - type: web
    name: datalyze-frontend
    env: node
    rootDir: datalyze-frontend
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    envVars:
      - key: NODE_VERSION
        value: 18
